### ISSUE TITLE
Name in two languages without any space between them

### ISSUE THREAD

**Issue by mancku** [wooorm/iso-3166#3]
Hi,

Hi,

I stumbled upon some names in the 2.js file that I'm not sure if they're 100% correct.
Code '**ES-A**' has '**AlicanteAlacant**' as a name. That is in fact Alicante (name of the region in Spanish) and Alacant (name of the region in Catalan) joined in a single word. Same happens in '**ES-CS**' - '**CastellónCastelló**' (Castellón in Spanish and Castelló in Catalan), '**ES-NA**' - '**Navarra, Comunidad Foral deNafarroako Foru Komunitatea**' (Navarra, Comunidad Foral de in Spanish, Nafarroako Foru Komunitatea in Basque) and '**ES-PV**' -  '**País VascoEuskal Herria**' (País Vasco in Spanish, Euskal Herria in Basque).

While the data is correct for those cases, as both names are official, the representation of the data, joining both without anything that indicates so, seems misleading. I think they'd be better with the local variant indicator, as 'LR-RI', 'MU-CC' and some others.

I'd be happy to do the PR myself but wanted to open the issue first to check that I'm not wrong about that.

Thank you

**Comment by wooorm** [comment]
hi!

The data is scraped.
Here’s the code that scrapes and cleans ISO 3166-2 code names: https://github.com/wooorm/iso-3166/blob/1dd1c6585a635611d3fcc057d1c314e31303dea4/build.js#L290-L307.
Here’s the WikiPedia page in question: https://en.wikipedia.org/wiki/ISO_3166-2:ES.

You’ll notice that they don’t explain the “normal” language. I think that that would solve it, on the WikiPedia page. Also for other people. So, something like this:

```
<a href="https://en.wikipedia.org/wiki/Province_of_Valencia">Valencia</a> (ES)<br>
València (CA)
```

If you want to dig into the code here, I have some ideas. But perhaps you want to change it on WikiPedia!
