### ISSUE TITLE
ISO Org

### ISSUE THREAD

**Issue by SourabhMulay** [wooorm/iso-3166#6]
The ISO codes and the mapping is collected from ISO.org??? 
Data is as per standards but still there are some extra information that user may need to implement some business logic. 
Can someone please confirm?

**Comment by wooorm** [comment]
no, read the readme: https://github.com/wooorm/iso-3166#what-is-this

**Comment by SourabhMulay** [comment]
Apologies. @wooorm Thanks for confirmation. Do you have any idea where can I get with ISO.org standards of states and Countries both. Because I currently need to pay for it and i don't want to.

**Comment by wooorm** [comment]
Did you read the readme? Please take 5 minutes to read what I wrote. Yes, you have to pay. That’s why this project doesn’t use it. That’s why this project exists.
