### ISSUE TITLE
Incorrect iso-3166-2 regions in the UK

### ISSUE THREAD

**Issue by jamesoneill997** [wooorm/iso-3166#8]
Upon selecting UK as a country, the sub-regions are a little bit off. 
![image](https://github.com/user-attachments/assets/afc5d725-9104-47b0-9c8e-8c4ee190ad93)

Doesn't seem to match up with these codes for iso-3166-2
https://www.iso.org/obp/ui/#iso:code:3166:GB

Example code:
```
  useEffect(() => {
    if (selectedCountry) {
      const subdivisions = iso31662.filter(subdivision => subdivision.parent === selectedCountry);
      setStateOptions(
        subdivisions.map(subdivision => ({
          label: subdivision.name,
          value: subdivision.code,
        }))
      );
    }
  }, [selectedCountry]);
```

**Comment by jamesoneill997** [comment]
Found that most regions in the UK are under the country within the UK, for example GB-ENG. So this might be a bit of an issue with iso-3166-2 in general as opposed to being an issue with this repo. Feel free to close if there's nothing to be added here.

**Comment by wooorm** [comment]
I don’t understand what the “bug” is supposed to be?
This package exposes JSON, not a UI. The data is crawled, if the data matches what is on wikipedia, then this repo is correct and you have a problem with iso.
If it doesn’t, that’s a bug here.
